string name         # control mode name
bool activate       # Whether to activate the control mode when loaded
# Type should be inferred from parameter file

---
bool ok             # Whether loading was successful
string message      # Any associated error message, or the empty if no error
