# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import time


# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'teleop_modular'
author = 'Bailey Chessum'
year = time.strftime("%Y")
copyright = "{}, {}".format(time.strftime("%Y"), author)
release = 'v0.1.1'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx_rtd_theme',
    'sphinx.ext.autodoc',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"



# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'

html_theme_options = {
    "collapse_navigation": True,
    "sticky_navigation": True,
    "navigation_depth": -1,
    # Only display the logo image, do not display the project name at the top of the sidebar
    # "logo_only": True,
}

html_static_path = ['_static']

html_context = {
    "display_github": True,
    "github_user": "BaileyChessum",
    "github_repo": "teleop_modular",
    "github_version": "main/",
    "conf_py_path": "docs/",
    "source_suffix": ".rst",
    "favicon": "logo.ico",
    "logo": "logo.svg"
}

html_favicon = "images/logo.ico"
html_logo = "images/logo.svg"

github_url = "https://github.com/BaileyChessum/teleop_modular"



